Fix exception thrown by kobold.modeltype in Lua
Fixes this exception:
  File "aiserver.py", line 3389, in lua_get_modeltype
    hidden_size = get_hidden_size_from_model(model)
NameError: name 'get_hidden_size_from_model' is not defined

The kobold.modeltype method eventually attempts to call
get_hidden_size_from_model in Python, but this method
was previously defined only within a local scope and so
is not visible from within lua_get_modeltype.  Since
get_hidden_size_from_model only accesses its model argument,
there is no reason not to make it a module-level method.

Also change the severity of several more Lua error logs to error.